baseURL: "https://buyuksoy.me/"
languageCode: en-us
title: Mustafa Büyüksoy
theme: PaperMod

params:
  env: production
  homeInfoParams:
    Content: 'My thoughts about Programming, Books and various other stuff'
  socialIcons:
    - name: twitter
      url: 'https://twitter.com/mbyksy'
    - name: linkedin
      url: 'https://www.linkedin.com/in/byksy/'
    - name: github
      url: 'https://github.com/byksy'
  assets:
    favicon: "img/favicon.ico"
    favicon16x16:  "img/favicon-16x16.png"
    favicon32x32:  "img/favicon-16x16.png"
    apple_touch_icon:  "img/apple-touch-icon.png"
    safari_pinned_tab:  "img/android-chrome-512x512.png"

  cover:
    linkFullImages: true
  ShowReadingTime: true
  

menu:
  main: 
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: false
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false